spring:
  redis:
    host: localhost
    port: 6379
    password:
  cloud:
    gateway:
      discovery:
        locator:
          lowerCaseServiceId: true
          enabled: true
      routes:
        # 医院服务
        - id: ruoyi-hospital
          uri: lb://ruoyi-hospital
          predicates:
            - Path=/hospital/**
          filters:
            - StripPrefix=1

security:
  # 不校验白名单
  ignore:
    whites:
      - /auth/logout
      - /auth/login
      - /auth/register
      - /*/v2/api-docs
      - /csrf
